- name: Deploy Node Exporter
  hosts: exporters
  become: yes

  roles:
    - ansible_node_exporter_role
- name: Deploy Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus
- name: Deploy Grafana
  hosts: grafana
  become: yes
  roles:
    - grafana


